---
title: "Finalize Study Sample"
author: "Valerie Jill Sydnor"
output:
  html_document:
    code_folding: show
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(dplyr)
```

# Initial Participant List

```{r}
#list of RBC ids with processed, non-variant resting state fMRI data: ses-PNC1_task-rest_acq-singleband_space-fsLR_den-91k, N = 1374
participants <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/sample_info/PNC/PNC_timeseries_processed.txt", header=F)
colnames(participants) <- c("rbcid") 
```

# Match rbcid, bblid, and scanid

```{r}
id.key <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/sample_info/PNC/bblid_scanid_reid.csv") #bblid-scanid-rbcid match
id.key$rbcid <- paste0("sub-", id.key$rbcid)
id.key <- left_join(participants, id.key, by="rbcid") #ids for 1374 participants with resting fMRI
```

# Construct Final Sample

Health Exclude
```{r}
healthexclude <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/sample_info/PNC/n1601_health_20170421.csv")
healthinclude <- healthexclude %>% filter(healthExcludev2 == 0) %>% dplyr::select(scanid) 

id.key.final <- id.key[id.key$scanid %in% healthinclude$scanid,] #remove 120 health exclude participants from the initial sample of 1374 with resting fMRI, remaining N = 1254
```

T1 Exclude
```{r}
T1exclude <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/sample_info/PNC/n1601_t1QaData_20170306.csv")
T1include <- T1exclude %>% filter(t1Exclude == 0) %>% dplyr::select(scanid)

id.key.final <- id.key.final[id.key.final$scanid %in% T1include$scanid,] #remove 23 participants with bad T1 data, remaining N = 1231
```

Resting State fMRI Motion Exclude
```{bash, echo=T, eval=T}
cd /cbica/projects/spatiotemp_dev_plasticity/Timeseries/qc_files
touch RBC_PNC_relMeansRMSMotion.csv
echo "rbcid,RMSmotion" >> RBC_PNC_relMeansRMSMotion.csv
for qcfile in sub*csv ; do
RMS=$(awk -F "," 'NR == 2 {print $8}' $qcfile)
RMS=$(printf "%.5f\n" "$RMS")
rbcid=${qcfile%%_*}
echo "$rbcid,$RMS" >> RBC_PNC_relMeansRMSMotion.csv
done
```
```{r}
#fMRI motion: then read the spreadsheet in to R
relRMS <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/Timeseries/qc_files/RBC_PNC_relMeansRMSMotion.csv")
```

```{r}
fMRIinclude <- relRMS %>% filter(RMSmotion < .2) %>% dplyr::select(rbcid)
id.key.final <- id.key.final[id.key.final$rbcid %in% fMRIinclude$rbcid,] #remove 179 participants with fMRI mean relative RMS motion > 0.2, remaining N = 1052
```

Fluctuation Amplitude Outlier Exclude
```{r}
fluctuations.glasser <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/PNC/fluctuationamplitude_subxregion_glasser360.csv") #regional fluctuation amplitude spreadsheet generated by fluctuation_amplitude/parcellate.Rmd
fluctuations.glasser <- fluctuations.glasser[fluctuations.glasser$rbcid %in% id.key.final$rbcid,] #data for just the remaining N = 1052 for outlier identification
```

```{r}
findoutliers <- function(input, outlierlevel){
  mean <- mean(input)
  stddev <- sd(input)
  lowerbound <- mean-(outlierlevel*stddev) 
  upperbound <- mean+(outlierlevel*stddev)

  outlier.logical <- input > upperbound | input < lowerbound
  
  return(outlier.logical)}

outlier.logical.matrix <- as.data.frame(lapply(fluctuations.glasser[2:361], function(x){findoutliers(x,4)})) #identify outliers on a parcel (column) basis, based on threshold of +- 4 SD from the mean
outlier.counts <- as.data.frame(rowSums(outlier.logical.matrix)) #determine how many parcels each participant (row) is an outlier in 
outliers <- outlier.counts$`rowSums(outlier.logical.matrix)` > 18 #identify participants with outlier data in more than 5% of glasser parcels
outliers <- as.data.frame(outliers)
outliers$rbcid <- fluctuations.glasser$rbcid

outlierinclude <- outliers %>% filter(outliers == FALSE) %>% dplyr::select(rbcid)
id.key.final <- id.key.final[id.key.final$rbcid %in% outlierinclude$rbcid,] #remove 19 participants with outlier fluctuation amplitude data from the 1052, FINAL N = 1033
```

# Save Final Sample (N=1033)

```{r}
write.csv(id.key.final, "/cbica/projects/spatiotemp_dev_plasticity/sample_info/PNC/FinalSample_spatiotempdevplasticity_N1033.csv", quote = F, row.names = F)
```
