# MODEL FITTING: AGE DEPENDENT CHANGES IN REGIONAL FLUCTUATION AMPLITUDE

library(dplyr)
library(cifti)
source("/cbica/projects/spatiotemp_dev_plasticity/code/spatiotemp_dev_plasticity/gam_models/GAM_functions.R")

# Prepare Fluctuation Amplitude, Demographics, and fMRI Motion data frame for GAMs

participants <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/sample_info/PNC/FinalSample_spatiotempdevplasticity_N1033.csv") #final study sample IDs, generated by sample_construction/finalsample.Rmd

demographics <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/sample_info/PNC/n1601_demographics_go1_20161212.csv") #PNC demographics information
demographics <- demographics %>% mutate(age = (ageAtScan1/12)) #format age variable into years
demographics$sex <- as.factor(demographics$sex) #format sex variable into a factor
demographics <- merge(participants, demographics, by="scanid", sort = F) #get demographics for the final study sample only via scanid matching
relMeansRMSMotion <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/Timeseries/qc_files/RBC_PNC_relMeansRMSMotion.csv") #RMS motion spreadsheet, generated by sample_construction/finalsample.Rmd
demographics <- merge(demographics, relMeansRMSMotion, by="rbcid", sort = F) #add fMRI motion information to demographics df

subxparcel.matrix.glasser <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/PNC/fluctuationamplitude_subxregion_glasser360.csv") #participant x glasser region fluctuation amplitude spreadsheet, generated by fluctuation_amplitude/parcellate.Rmd
fluctuations.glasser.pnc <- merge(subxparcel.matrix.glasser, demographics, by="rbcid", sort = F) #combine participant demographics and fluctuation amplitude data
write.csv(fluctuations.glasser.pnc, "/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/PNC/glasserfluctuations_demographics_finalsample.csv", quote = F, row.names = F)
subxparcel.matrix.schaefer <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/PNC/fluctuationamplitude_subxregion_schaefer400.csv") #participant x schaefer region fluctuation amplitude spreadsheet, generated by fluctuation_amplitude/parcellate.Rmd
fluctuations.schaefer.pnc <- merge(subxparcel.matrix.schaefer, demographics, by="rbcid", sort = F) #combine participant demographics and fluctuation amplitude data
write.csv(fluctuations.schaefer.pnc, "/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/PNC/schaeferfluctuations_demographics_finalsample.csv" , quote = F, row.names = F)

glasser.parcel.labels <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/Maps/parcellations/surface/glasser360_regionlist.csv", header = T) #glasser parcel names in order of surface data
schaefer.parcel.labels <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/Maps/parcellations/surface/schaefer400_regionlist.csv", header = T) #schaefer parcel names in order of surface data

###################################################################################################

# Fit GAM Models (Age Effects)

## Region-wise GAM Statistics and Derivate-based Temporal Developmental Properties

gam.age.glasser <- matrix(data=NA, nrow=360, ncol=10) #matrix to save gam.fit output to

for(row in c(1:nrow(glasser.parcel.labels))){ #for each glasser region
  region <- glasser.parcel.labels$label[row] 
  GAM.RESULTS <- gam.fit.smooth(measure = "fluctuations", atlas = "glasser", dataset = "pnc", region = region, smooth_var = "age", covariates = "sex + RMSmotion", knots = 3, set_fx = TRUE, stats_only = FALSE) #run the gam.fit.smooth function
  gam.age.glasser[row,] <- GAM.RESULTS} #and append results to output df 

gam.age.glasser <- as.data.frame(gam.age.glasser)
colnames(gam.age.glasser) <- c("label","GAM.age.Fvalue","GAM.age.pvalue","GAM.age.partialR2","Anova.age.pvalue","age.onsetchange","age.peakchange","minage.decrease","maxage.increase","age.maturation") #region name, GAM F-value for the age smooth term, GAM p-value for the age smooth term, partial Rsq from age and age-null models, Anova p-value comparing age and age-null models, age at which fluctuation amplitude starts significantly changing (first significant derivative), age at which fluctuation amplitude exhibits maximal change (largest significant derivative), age at which fluctuation amplitude starts significantly decreasing (first significant negative derivative), age at which fluctuation amplitude stops significantly increasing (last significant positive derivative), age at which fluctuation amplitude stops changing (last significant derivative)
cols = c(2:10)    
gam.age.glasser[,cols] = apply(gam.age.glasser[,cols], 2, function(x) as.numeric(as.character(x))) #format as numeric
write.csv(gam.age.glasser, "/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/fluctuationamplitude_age_statistics_glasser.csv", row.names = F, quote = F)


gam.age.schaefer <- matrix(data=NA, nrow=400, ncol=10) 

for(row in c(1:nrow(schaefer.parcel.labels))){ #for each schaefer region
  region <- schaefer.parcel.labels$label[row] 
  GAM.RESULTS <- gam.fit.smooth(measure = "fluctuations", atlas = "schaefer", dataset = "pnc", region = region, smooth_var = "age", covariates = "sex + RMSmotion", knots = 3, set_fx = TRUE, stats_only = FALSE) #run the gam.fit.smooth function
  gam.age.schaefer[row,] <- GAM.RESULTS} #and append results to output df 

gam.age.schaefer <- as.data.frame(gam.age.schaefer)
colnames(gam.age.schaefer) <- c("label","GAM.age.Fvalue","GAM.age.pvalue","GAM.age.partialR2","Anova.age.pvalue","age.onsetchange","age.peakchange","minage.decrease","maxage.increase","age.maturation")
cols = c(2:10)    
gam.age.schaefer[,cols] = apply(gam.age.schaefer[,cols], 2, function(x) as.numeric(as.character(x)))
write.csv(gam.age.schaefer, "/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/fluctuationamplitude_age_statistics_schaefer.csv", row.names = F, quote = F)

###################################################################################################

## Region-wise GAM Smooth Predictions

np <- 200
gam.smooths.glasser <- matrix(data=NA, ncol=7) #empty matrix to save gam.smooth.predict output to
colnames(gam.smooths.glasser) <- c("age","fitted","se","lower","upper","index","label")

gam.peaks.glasser <- matrix(data=NA, ncol=2) #empty matrix to save predicted measure peaks to (age at which fluctuation amplitude is predicted to be maximal)
colnames(gam.peaks.glasser) <- c("label","age.peak")

for(row in c(1:nrow(glasser.parcel.labels))){ #for each glasser region
  region <- glasser.parcel.labels$label[row] 
  GAM.SMOOTH <- gam.smooth.predict(measure = "fluctuations", atlas = "glasser", dataset = "pnc", region = region, smooth_var = "age", covariates = "sex + RMSmotion", knots = 3, set_fx = TRUE, increments = np) #run the gam.smooth.predict function
  preddata <- as.data.frame(GAM.SMOOTH[3]) #get predicted.smooth df from function output
  preddata$index <- rep(x=row, np) #region index
  preddata$label <- rep(x=GAM.SMOOTH[1], np) #label
  gam.smooths.glasser <- rbind(gam.smooths.glasser, preddata)
  datapeak <- as.data.frame(cbind(GAM.SMOOTH[1], GAM.SMOOTH[2])) #label and predicted fluctuation amplitude peak
  colnames(datapeak) <- c("label","age.peak")
  gam.peaks.glasser <- rbind(gam.peaks.glasser, datapeak)
}

gam.smooths.glasser <- gam.smooths.glasser[-1,] #remove empty initialization row
gam.smooths.glasser$label <- as.character(gam.smooths.glasser$label)
gam.peaks.glasser <- gam.peaks.glasser[-1,] #remove empty initialization row
gam.peaks.glasser$label <- as.character(gam.peaks.glasser$label)
gam.peaks.glasser$age.peak <- as.numeric(gam.peaks.glasser$age.peak)
write.csv(gam.smooths.glasser,"/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/fluctuationamplitude_age_predictedsmooths_glasser.csv", row.names = F, quote = F) 
write.csv(gam.peaks.glasser, "/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/fluctuationamplitude_age_peaks_glasser.csv", row.names = F, quote = F)


np <- 200
gam.smooths.schaefer <- matrix(data=NA, ncol=7) 
colnames(gam.smooths.schaefer) <- c("age","fitted","se","lower","upper","index","label")

gam.peaks.schaefer <- matrix(data=NA, ncol=2) 
colnames(gam.peaks.schaefer) <- c("label","age.peak")

for(row in c(1:nrow(schaefer.parcel.labels))){ #for each schaefer region
  region <- schaefer.parcel.labels$label[row] 
  GAM.SMOOTH <- gam.smooth.predict(measure = "fluctuations", atlas = "schaefer", dataset = "pnc", region = region, smooth_var = "age", covariates = "sex + RMSmotion", knots = 3, set_fx = TRUE, increments = np) #run the gam.smooth.predict function
  preddata <- as.data.frame(GAM.SMOOTH[3]) #get predicted.smooth df from function output
  preddata$index <- rep(x=row, np) #region index
  preddata$label <- rep(x=GAM.SMOOTH[1], np) #label
  gam.smooths.schaefer <- rbind(gam.smooths.schaefer, preddata)
  datapeak <- as.data.frame(cbind(GAM.SMOOTH[1], GAM.SMOOTH[2])) #label and predicted fluctuation amplitude peak
  colnames(datapeak) <- c("label","age.peak")
  gam.peaks.schaefer <- rbind(gam.peaks.schaefer, datapeak)
}

gam.smooths.schaefer <- gam.smooths.schaefer[-1,] #remove empty initialization row
gam.smooths.schaefer$label <- as.character(gam.smooths.schaefer$label)
gam.peaks.schaefer <- gam.peaks.schaefer[-1,] #remove empty initialization row
gam.peaks.schaefer$label <- as.character(gam.peaks.schaefer$label)
gam.peaks.schaefer$age.peak <- as.numeric(gam.peaks.schaefer$age.peak)
write.csv(gam.smooths.schaefer,"/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/fluctuationamplitude_age_predictedsmooths_schaefer.csv", row.names = F, quote = F) 
write.csv(gam.peaks.schaefer, "/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/fluctuationamplitude_age_peaks_schaefer.csv", row.names = F, quote = F)

###################################################################################################

### GAM Smooth Predictions: Age of Peak Fluctuation Amplitude Credible Intervals

np <- 200 #number of predictions
npd <- 10000 #number of posterior draws
gam.peaks.glasser <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/fluctuationamplitude_age_peaks_glasser.csv")
posterior.peaks <- matrix(data=NA, ncol=3) 
colnames(posterior.peaks) <- c("label","peak.lower.CI","peak.upper.CI")

for(row in c(1:nrow(glasser.parcel.labels))){ #for each glasser region
  region <- glasser.parcel.labels$label[row] 
  POSTERIOR.SMOOTHS <- gam.posterior.smooths(measure = "fluctuations", atlas = "glasser", dataset = "pnc", region = region, smooth_var = "age", covariates = "sex + RMSmotion", knots = 3, set_fx = TRUE, draws = npd, increments = np, return_draws = FALSE) #run the gam.posterior.smooths function
  datapeak <- as.data.frame(cbind(POSTERIOR.SMOOTHS[[1]], POSTERIOR.SMOOTHS[[3]], POSTERIOR.SMOOTHS[[4]]))
  colnames(datapeak) <- c("label","peak.lower.CI","peak.upper.CI")
  posterior.peaks <- rbind(posterior.peaks, datapeak)
}

posterior.peaks <- posterior.peaks[-1,] #remove empty initialization row
gam.peaks.glasser <- merge(gam.peaks.glasser, posterior.peaks, by="label", sort=F)
cols = c(2:4)    
gam.peaks.glasser[,cols] = apply(gam.peaks.glasser[,cols], 2, function(x) as.numeric(as.character(x)))
write.csv(gam.peaks.glasser, "/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/fluctuationamplitude_age_peaks_glasser.csv", row.names = F, quote = F)


np <- 200 #number of predictions
npd <- 10000  #number of posterior draws
gam.peaks.schaefer <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/fluctuationamplitude_age_peaks_schaefer.csv")
posterior.peaks <- matrix(data=NA, ncol=3) 
colnames(posterior.peaks) <- c("label","peak.lower.CI","peak.upper.CI")

for(row in c(1:nrow(schaefer.parcel.labels))){ #for each schaefer region
  region <- schaefer.parcel.labels$label[row] 
  POSTERIOR.SMOOTHS <- gam.posterior.smooths(measure = "fluctuations", atlas = "schaefer", dataset = "pnc", region = region, smooth_var = "age", covariates = "sex + RMSmotion", knots = 3, set_fx = TRUE, draws = npd, increments = np, return_draws = FALSE) #run the gam.posterior.smooths function
  datapeak <- as.data.frame(cbind(POSTERIOR.SMOOTHS[[1]], POSTERIOR.SMOOTHS[[3]], POSTERIOR.SMOOTHS[[4]]))
  posterior.peaks
  colnames(datapeak) <- c("label","peak.lower.CI","peak.upper.CI")
  posterior.peaks <- rbind(posterior.peaks, datapeak)
}

posterior.peaks <- posterior.peaks[-1,] #remove empty initialization row
gam.peaks.schaefer <- merge(gam.peaks.schaefer, posterior.peaks, by="label", sort=F)
cols = c(2:4)    
gam.peaks.schaefer[,cols] = apply(gam.peaks.schaefer[,cols], 2, function(x) as.numeric(as.character(x)))
write.csv(gam.peaks.schaefer, "/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/fluctuationamplitude_age_peaks_schaefer.csv", row.names = F, quote = F)

###################################################################################################

## Region-wise Developmental Derivatives

np <- 200 #number of predictions
npd <- 1 #not drawing from the posterior here
gam.derivatives.glasser <- matrix(data=NA, ncol=9) 
colnames(gam.derivatives.glasser) <- c("age","derivative","se","lower","upper","significant","significant.derivative","index","label")

for(row in c(1:nrow(glasser.parcel.labels))){ #for each glasser region
  region <- glasser.parcel.labels$label[row] 
  GAM.DERIVATIVES <- gam.derivatives(measure = "fluctuations", atlas = "glasser", dataset = "pnc", region = region, smooth_var = "age", covariates = "sex + RMSmotion", knots = 3, set_fx = TRUE, draws = npd, increments = np, return_posterior_derivatives = FALSE) #run the gam.derivatives function
  GAM.DERIVATIVES$index <- as.numeric(rep(x=row, np)) #region index
  GAM.DERIVATIVES$label <- as.character(rep(x=region, np)) #region label
  gam.derivatives.glasser <- rbind(gam.derivatives.glasser, GAM.DERIVATIVES)
}

gam.derivatives.glasser <- gam.derivatives.glasser[-1,] #remove empty initialization row
write.csv(gam.derivatives.glasser, "/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/fluctuationamplitude_age_derivatives_glasser.csv", row.names = F, quote = F)


np <- 200 #number of predictions
npd <- 1 #not drawing from the posterior here
gam.derivatives.schaefer<- matrix(data=NA, ncol=9) 
colnames(gam.derivatives.schaefer) <- c("age","derivative","se","lower","upper","significant","significant.derivative","index","label")

for(row in c(1:nrow(schaefer.parcel.labels))){ #for each glasser region
  region <- schaefer.parcel.labels$label[row] 
  GAM.DERIVATIVES <- gam.derivatives(measure = "fluctuations", atlas = "schaefer", dataset = "pnc", region = region, smooth_var = "age", covariates = "sex + RMSmotion", knots = 3, set_fx = TRUE, draws = npd, increments = np, return_posterior_derivatives = FALSE) #run the gam.derivatives function
  GAM.DERIVATIVES$index <- as.numeric(rep(x=row, np)) #region index
  GAM.DERIVATIVES$label <- as.character(rep(x=region, np)) #region label
  gam.derivatives.schaefer <- rbind(gam.derivatives.schaefer, GAM.DERIVATIVES)
}

gam.derivatives.schaefer <- gam.derivatives.schaefer[-1,] #remove empty initialization row
write.csv(gam.derivatives.schaefer, "/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/fluctuationamplitude_age_derivatives_schaefer.csv", row.names = F, quote = F)

###################################################################################################

### Region-wise Posterior Smooth Derivatives Correlation with Sensorimotor-Association Axis

np <- 200 #number of predictions
npd <- 10000 #number of posterior draws
gam.derivatives.glasser <- matrix(data=NA, ncol=5) #empty matrix to save gam.derivatives output to
colnames(gam.derivatives.glasser) <- c("label", "index", "age", "draw", "posterior.derivative")

for(row in c(1:nrow(glasser.parcel.labels))){ #for each glasser region
  region <- glasser.parcel.labels$label[row] 
  GAM.DERIVATIVES <- gam.derivatives(measure = "fluctuations", atlas = "glasser", dataset = "pnc", region = region, smooth_var = "age", covariates = "sex + RMSmotion", knots = 3, set_fx = TRUE, draws = npd, increments = np, return_posterior_derivatives = TRUE) #run the gam.derivatives function
  GAM.DERIVATIVES$index <- as.numeric(rep(x=row, (np*npd))) #region index
  GAM.DERIVATIVES$label <- as.character(rep(x=region, (np*npd))) #region label
  GAM.DERIVATIVES <- GAM.DERIVATIVES %>% select(label, index, age, draw, posterior.derivative)
  gam.derivatives.glasser <- rbind(gam.derivatives.glasser, GAM.DERIVATIVES)
}

gam.derivatives.glasser <- gam.derivatives.glasser[-1,] #remove empty initialization row

# Compute and save correlations with S-A axis
S.A.axis.cifti <- read_cifti("/cbica/projects/spatiotemp_dev_plasticity/Maps/S-A_ArchetypalAxis/FSLRVertex/SensorimotorAssociation_Axis_parcellated/SensorimotorAssociation.Axis.Glasser360.pscalar.nii") #S-A_ArchetypalAxis repo
S.A.axis <- as.data.frame(cbind(rank(S.A.axis.cifti$data), names(S.A.axis.cifti$Parcel)))
colnames(S.A.axis) <- c("SA.axis","orig_parcelname")
S.A.axis <- merge(S.A.axis, glasser.parcel.labels, by="orig_parcelname", sort = F)
rm(S.A.axis.cifti)

SNR.mask <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/Maps/parcellations/surface/SNRmask_glasser360.csv")

gam.derivatives.glasser <- merge(S.A.axis, gam.derivatives.glasser, by="label", sort=F) #assign axis rank to each label
gam.derivatives.glasser <- merge(SNR.mask, gam.derivatives.glasser, by="label", sort=F) 
gam.derivatives.glasser <- gam.derivatives.glasser %>% filter(SNR.mask != 0) #include only high SNR parcels (N=336) in analyses

corr_values <- gam.derivatives.glasser %>%
  group_by(draw,age) %>%
  do(SAcorrelation = cor(as.numeric(.$SA.axis), as.numeric(.$posterior.derivative))) %>%
  unnest(cols = c(SAcorrelation))

corr_values.wide <- corr_values %>% pivot_wider(names_from = "draw", values_from = "SAcorrelation")
write.csv(corr_values.wide, "/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/SAaxis_posteriorderivative_correlation_byage_glasser.csv", row=F, quote=F)


np <- 200 #number of predictions
npd <- 10000 #number of posterior draws
gam.derivatives.schaefer <- matrix(data=NA, ncol=5) #empty matrix to save gam.derivatives output to
colnames(gam.derivatives.schaefer) <- c("label", "index", "age", "draw", "posterior.derivative")

for(row in c(1:nrow(schaefer.parcel.labels))){ #for each glasser region
  region <- schaefer.parcel.labels$label[row] 
  GAM.DERIVATIVES <- gam.derivatives(measure = "fluctuations", atlas = "schaefer", dataset = "pnc", region = region, smooth_var = "age", covariates = "sex + RMSmotion", knots = 3, set_fx = TRUE, draws = npd, increments = np, return_posterior_derivatives = TRUE) #run the gam.derivatives function
  GAM.DERIVATIVES$index <- as.numeric(rep(x=row, (np*npd))) #region index
  GAM.DERIVATIVES$label <- as.character(rep(x=region, (np*npd))) #region label
  GAM.DERIVATIVES <- GAM.DERIVATIVES %>% select(label, index, age, draw, posterior.derivative)
  gam.derivatives.schaefer <- rbind(gam.derivatives.schaefer, GAM.DERIVATIVES)
}

gam.derivatives.schaefer <- gam.derivatives.schaefer[-1,] #remove empty initialization row

# Compute and save correlations with S-A axis
S.A.axis.cifti <- read_cifti("/cbica/projects/spatiotemp_dev_plasticity/Maps/S-A_ArchetypalAxis/FSLRVertex/SensorimotorAssociation_Axis_parcellated/SensorimotorAssociation.Axis.Schaefer400.17Networks.pscalar.nii") #S-A_ArchetypalAxis repo
S.A.axis <- as.data.frame(cbind(rank(S.A.axis.cifti$data), names(S.A.axis.cifti$Parcel)))
colnames(S.A.axis) <- c("SA.axis","orig_parcelname")
S.A.axis$label <- schaefer.parcel.labels$label
rm(S.A.axis.cifti)

SNR.mask <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/Maps/parcellations/surface/SNRmask_schaefer400.csv")

gam.derivatives.schaefer <- merge(S.A.axis, gam.derivatives.schaefer, by="label", sort=F) #assign axis rank to each label
gam.derivatives.schaefer <- merge(SNR.mask, gam.derivatives.schaefer, by="label", sort=F) 
gam.derivatives.schaefer <- gam.derivatives.schaefer %>% filter(SNR.mask != 0) #include only high SNR parcels (N=336) in analyses

corr_values <- gam.derivatives.schaefer %>%
  group_by(draw,age) %>%
  do(SAcorrelation = cor(as.numeric(.$SA.axis), as.numeric(.$posterior.derivative))) %>%
  unnest(cols = c(SAcorrelation))

corr_values.wide <- corr_values %>% pivot_wider(names_from = "draw", values_from = "SAcorrelation")
write.csv(corr_values.wide, "/cbica/projects/spatiotemp_dev_plasticity/FluctuationAmplitude/GAMRESULTS/SAaxis_posteriorderivative_correlation_byage_schaefer.csv", row=F, quote=F)